name: future_goodies
author: Wilker LÃºcio <wilkerlucio@gmail.com>
version: 0.6.0
homepage: http://wilker-dev.com/future_goodies
description: Future helper libraries for async management.
dev_dependencies:
  unittest: any
